export const STATUS_OPTIONS = ['ALL', 'NEW', 'CONTACTED', 'INTERESTED', 'FOLLOW_UP', 'VISITED', 'APPLICATION_STARTED', 'CONVERTED', 'FAILED', 'RE_ENGAGED'];
export const SCORE_OPTIONS = ['ALL', 'HOT', 'WARM', 'COLD'];
export const SOURCE_OPTIONS = ['ALL', 'WEBSITE', 'FACEBOOK', 'GOOGLE_ADS', 'INSTAGRAM', 'JUSTDIAL', 'WALK_IN', 'REFERRAL', 'PHONE_INQUIRY', 'EMAIL_INQUIRY', 'EVENT', 'WHATSAPP', 'CAMPAIGN'];
